# This is a Markdownlint configuration file to ignore the acceptable issues for all files.
MD041: false # First line in file should be a top level header.
MD013: false # Line length.
MD033: false # Inline HTML.
