name: Lint

on: pull_request

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check -recursive
